[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
contracts_hui = "3EpcS5dv1G71CDER3d77L7jAh7dn9zKpJNo7wSSwn7kA"

[programs.devnet]
contracts_hui = "3EpcS5dv1G71CDER3d77L7jAh7dn9zKpJNo7wSSwn7kA"

[programs.testnet]
contracts_hui = "3EpcS5dv1G71CDER3d77L7jAh7dn9zKpJNo7wSSwn7kA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "target/deploy/phantom-account2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"