[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
contracts_hui = "73N3XxT1FGJt2sZmtVbiuD3TcF2f6bLffMqUi7PJQZk9"

[programs.devnet]
contracts_hui = "73N3XxT1FGJt2sZmtVbiuD3TcF2f6bLffMqUi7PJQZk9"

[programs.testnet]
contracts_hui = "73N3XxT1FGJt2sZmtVbiuD3TcF2f6bLffMqUi7PJQZk9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"