[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
<<<<<<< HEAD
contracts_hui = "73N3XxT1FGJt2sZmtVbiuD3TcF2f6bLffMqUi7PJQZk9"

[programs.devnet]
contracts_hui = "73N3XxT1FGJt2sZmtVbiuD3TcF2f6bLffMqUi7PJQZk9"

[programs.testnet]
contracts_hui = "73N3XxT1FGJt2sZmtVbiuD3TcF2f6bLffMqUi7PJQZk9"
=======
contracts_hui = "5S8b4n1VwN3wasBcheSdUKSMyvVPLMgMe9FLxWLfBT8t"

[programs.devnet]
contracts_hui = "5S8b4n1VwN3wasBcheSdUKSMyvVPLMgMe9FLxWLfBT8t"

[programs.testnet]
contracts_hui = "5S8b4n1VwN3wasBcheSdUKSMyvVPLMgMe9FLxWLfBT8t"
>>>>>>> e2bd6cb0551c905b610c043cda1bfe18e063fd80

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"