[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts_hui = "Ak59apPA2FJJrtTRRojeCjWWmPXc1shpzxXrsaKApaFX"

[registry]
url = "https://api.apr.dev"
[workspace]
members = ["contracts/hui"]
[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
